/**
 * Centralized site configuration.
 *
 * This is the ONLY place business data, trust claims, partner/lead-routing
 * details and third-party IDs are declared. Components must never hard-code
 * a phone number, a review count, a claim about hours/response time, an
 * analytics ID or a WhatsApp URL.
 *
 * Every field below that is `null` (or `false`) represents a fact we cannot
 * currently verify. Components that display such a fact must check for
 * `null` and render nothing rather than fall back to placeholder or
 * invented copy. See README section "Configuration" for the full list of
 * what's pending.
 */

export type OperationalMode = "asset" | "lead-partner" | "operator";

export interface BusinessInfo {
  businessName: string | null;
  legalName: string | null;
  phone: string | null;
  phoneDisplay: string | null;
  whatsapp: string | null;
  email: string | null;
  address: string | null;
  googleMapsUrl: string | null;
}

export interface TrustClaims {
  openingHours: string | null;
  responseTime: string | null;
  warranty: string | null;
  reviewRating: number | null;
  reviewCount: number | null;
  yearsInBusiness: number | null;
  technicianCount: number | null;
  customerCount: number | null;
  licenseNumber: string | null;
  vehicleAccessCapability: string | null;
}

export interface Brands {
  batteryBrands: string[];
  authorizedBrands: string[];
}

export interface Analytics {
  gaMeasurementId: string | null;
  googleSiteVerification: string | null;
  googleAdsConversionId: string | null;
  metaPixelId: string | null;
}

/**
 * A named third-party service provider that receives leads generated by this
 * site. Numbers live here — never in components. If a number is `null`, any
 * CTA that depends on it must not render (see LeadActions).
 */
export interface PartnerConfig {
  enabled: boolean;
  name: string;
  /** Digits only, no `+` or spaces — e.g. "9715XXXXXXXX". Used for wa.me. */
  whatsappNumber: string | null;
  /** E.164 with `+` — e.g. "+9715XXXXXXXX". Used for tel: links. */
  callNumber: string | null;
}

/**
 * Controls the shape of the outgoing WhatsApp lead message and how the
 * source is attributed. Message templates live in `src/lib/leads.ts` and
 * only reference these fields — never PII, never phone numbers, never any
 * analytics identifier.
 */
export interface LeadAttributionConfig {
  enabled: boolean;
  sourceName: string;
  includePartnerNameInWhatsAppMessage: boolean;
}

/**
 * Reserved for a future dedicated tracking DID. When `enabled` and `number`
 * are set, `getCallUrl()` prefers this over `partner.callNumber` so raw
 * partner numbers never appear in the DOM under a tracked scenario.
 */
export interface CallTrackingConfig {
  enabled: boolean;
  number: string | null;
}

export interface SiteConfig {
  operationalMode: OperationalMode;

  /**
   * Explicit, manually-set proof that a real, verified business entity
   * exists behind this site. Intentionally NOT derived from
   * operationalMode — moving out of "asset" mode is not itself evidence
   * of a verified entity. Only flip this to true once the business
   * details below have actually been confirmed.
   */
  entityVerified: boolean;

  siteName: string;
  siteUrl: string;
  locale: string;
  country: string;
  currency: string;

  defaultOgImage: string;

  business: BusinessInfo;
  claims: TrustClaims;
  serviceAreas: string[];
  brands: Brands;

  partner: PartnerConfig;
  leadAttribution: LeadAttributionConfig;
  callTracking: CallTrackingConfig;

  /** Where lead-form submissions go. Form only renders/submits when set. */
  leadEndpoint: string | null;

  analytics: Analytics;

  socialLinks: { label: string; url: string }[];
}

export const siteConfig: SiteConfig = {
  operationalMode: "lead-partner",

  entityVerified: false,

  siteName: "Dubai Battery Service",
  siteUrl: "https://dubaibatteryservice.com",
  locale: "en-AE",
  country: "AE",
  currency: "AED",

  defaultOgImage: "/og-image.png",

  business: {
    businessName: null,
    legalName: null,
    phone: null,
    phoneDisplay: null,
    whatsapp: null,
    email: null,
    address: null,
    googleMapsUrl: null,
  },

  claims: {
    openingHours: null,
    responseTime: null,
    warranty: null,
    reviewRating: null,
    reviewCount: null,
    yearsInBusiness: null,
    technicianCount: null,
    customerCount: null,
    licenseNumber: null,
    vehicleAccessCapability: null,
  },

  serviceAreas: [
    "Dubai Marina",
    "JLT",
    "Downtown Dubai",
    "Business Bay",
    "Jumeirah",
    "JVC",
    "Al Barsha",
    "Deira",
    "Palm Jumeirah",
  ],

  brands: {
    batteryBrands: [],
    authorizedBrands: [],
  },

  /**
   * Public-facing brand remains "Dubai Battery Service".
   * `partner.name` is used only inside outgoing lead messages and the
   * optional partner-disclosure line — it is never used as the site's
   * brand, headline, or logo text.
   */
    partner: {
    enabled: true,
    name: "Battery Boost Dubai",
    whatsappNumber: "971582424859",
    callNumber: "+971582424859",
  },

  leadAttribution: {
    enabled: true,
    sourceName: "DubaiBatteryService.com",
    includePartnerNameInWhatsAppMessage: true,
  },

  callTracking: {
    enabled: false,
    number: null,
  },

  leadEndpoint: null,

  analytics: {
    gaMeasurementId: null,
    googleSiteVerification: null,
    googleAdsConversionId: null,
    metaPixelId: null,
  },

  socialLinks: [],
};

/**
 * True only when entityVerified has been explicitly set to true. Being out
 * of "asset" mode is NOT sufficient on its own — operationalMode governs
 * copy tone and lead-handling, not schema.org verification claims.
 */
export const hasVerifiedEntity = siteConfig.entityVerified === true;
