/**
 * Centralized site configuration.
 *
 * This is the ONLY place business data, trust claims, partner/lead-routing
 * details and third-party IDs are declared. Components must never hard-code
 * a phone number, a review count, a claim about hours/response time, an
 * analytics ID or a WhatsApp URL.
 *
 * Every field below that is `null` (or `false`) represents a fact we cannot
 * currently verify. Components that display such a fact must check for
 * `null` and render nothing rather than fall back to placeholder or
 * invented copy. See README section "Configuration" for the full list of
 * what's pending.
 */

export type OperationalMode = "asset" | "lead-partner" | "operator";

export interface BusinessInfo {
  businessName: string | null;
  legalName: string | null;
  phone: string | null;
  phoneDisplay: string | null;
  whatsapp: string | null;
  email: string | null;
  address: string | null;
  googleMapsUrl: string | null;
}

export interface TrustClaims {
  openingHours: string | null;
  responseTime: string | null;
  warranty: string | null;
  reviewRating: number | null;
  reviewCount: number | null;
  yearsInBusiness: number | null;
  technicianCount: number | null;
  customerCount: number | null;
  licenseNumber: string | null;
  vehicleAccessCapability: string | null;
}

/**
 * A single indicative price band shown on /car-battery-prices-dubai/.
 *
 * These are RANGES, never quotes. The page says so in visible copy. They
 * exist because the URL, title and meta description all target "car
 * battery prices in Dubai" and the page previously contained no price
 * information whatsoever — it ranked for nothing and would have bounced
 * anyone who did land on it.
 */
export interface PriceBand {
  /** e.g. "Conventional flooded — small car" */
  label: string;
  /** e.g. "35-45 Ah" */
  spec: string;
  /** Typical vehicles, plain language. */
  fits: string;
  low: number;
  high: number;
}

export interface PricingConfig {
  /**
   * When false the whole price table is withheld and the page falls back
   * to explaining cost DRIVERS only — same null-discipline as `claims`.
   */
  showBands: boolean;
  /**
   * ⚠️ VERIFY BEFORE LAUNCH. These are indicative Dubai market ranges for
   * supply + standard on-site fitting, not partner pricing. Confirm them
   * against the partner's actual current list, then update
   * `lastReviewed`. Do not present them as quotes anywhere.
   */
  bands: PriceBand[];
  /** ISO date. Rendered on the page so a stale table is visibly stale. */
  lastReviewed: string;
  /** Additional line items that move a quote. */
  extras: { label: string; note: string }[];
}

export interface Brands {
  batteryBrands: string[];
  authorizedBrands: string[];
}

export interface Analytics {
  gaMeasurementId: string | null;
  googleSiteVerification: string | null;
  googleAdsConversionId: string | null;
  metaPixelId: string | null;
}

/**
 * A named third-party service provider that receives leads generated by this
 * site. Numbers live here — never in components. If a number is `null`, any
 * CTA that depends on it must not render (see LeadActions).
 */
export interface PartnerConfig {
  enabled: boolean;
  name: string;
  /** Digits only, no `+` or spaces — e.g. "9715XXXXXXXX". Used for wa.me. */
  whatsappNumber: string | null;
  /** E.164 with `+` — e.g. "+9715XXXXXXXX". Used for tel: links. */
  callNumber: string | null;
}

/**
 * Controls the shape of the outgoing WhatsApp lead message and how the
 * source is attributed. Message templates live in `src/lib/leads.ts` and
 * only reference these fields — never PII, never phone numbers, never any
 * analytics identifier.
 */
export interface LeadAttributionConfig {
  enabled: boolean;
  sourceName: string;
  includePartnerNameInWhatsAppMessage: boolean;
}

/**
 * Reserved for a future dedicated tracking DID. When `enabled` and `number`
 * are set, `getCallUrl()` prefers this over `partner.callNumber` so raw
 * partner numbers never appear in the DOM under a tracked scenario.
 */
export interface CallTrackingConfig {
  enabled: boolean;
  number: string | null;
}

export interface SiteConfig {
  operationalMode: OperationalMode;

  /**
   * Explicit, manually-set proof that a real, verified business entity
   * exists behind this site. Intentionally NOT derived from
   * operationalMode — moving out of "asset" mode is not itself evidence
   * of a verified entity. Only flip this to true once the business
   * details below have actually been confirmed.
   */
  entityVerified: boolean;

  siteName: string;
  siteUrl: string;
  locale: string;
  country: string;
  currency: string;

  defaultOgImage: string;

  business: BusinessInfo;
  claims: TrustClaims;
  pricing: PricingConfig;
  serviceAreas: string[];
  brands: Brands;

  partner: PartnerConfig;
  leadAttribution: LeadAttributionConfig;
  callTracking: CallTrackingConfig;

  /** Where lead-form submissions go. Form only renders/submits when set. */
  leadEndpoint: string | null;

  analytics: Analytics;

  socialLinks: { label: string; url: string }[];
}

export const siteConfig: SiteConfig = {
  operationalMode: "lead-partner",

  entityVerified: false,

  siteName: "Dubai Battery Service",
  siteUrl: "https://dubaibatteryservice.com",
  locale: "en-AE",
  country: "AE",
  currency: "AED",

  defaultOgImage: "/og-image.png",

  business: {
    businessName: null,
    legalName: null,
    phone: null,
    phoneDisplay: null,
    whatsapp: null,
    email: null,
    address: null,
    googleMapsUrl: null,
  },

  claims: {
    openingHours: null,
    responseTime: null,
    warranty: null,
    reviewRating: null,
    reviewCount: null,
    yearsInBusiness: null,
    technicianCount: null,
    customerCount: null,
    licenseNumber: null,
    vehicleAccessCapability: null,
  },

  pricing: {
    showBands: true,
    lastReviewed: "2026-09-05",
    bands: [
      {
        label: "Conventional flooded — small car",
        spec: "35–45 Ah",
        fits: "Yaris, Corolla, Sunny, Elantra and similar without stop-start",
        low: 220,
        high: 400,
      },
      {
        label: "Conventional flooded — mid-size",
        spec: "55–75 Ah",
        fits: "Camry, Accord, Altima, mid-size saloons without stop-start",
        low: 350,
        high: 650,
      },
      {
        label: "EFB — stop-start",
        spec: "60–75 Ah",
        fits: "Many stop-start models where the maker specifies EFB, not AGM",
        low: 450,
        high: 800,
      },
      {
        label: "AGM — stop-start / heavy electronics",
        spec: "60–80 Ah",
        fits: "German saloons and crossovers with battery management",
        low: 700,
        high: 1400,
      },
      {
        label: "AGM — large SUV",
        spec: "90–105 Ah",
        fits: "Patrol, Land Cruiser, large premium SUVs",
        low: 1000,
        high: 2000,
      },
    ],
    extras: [
      {
        label: "On-site fitting",
        note: "Usually included in a mobile quote. Ask — if it is priced separately, that changes the comparison.",
      },
      {
        label: "BMS / battery registration",
        note: "Required by many German makes. Typically a small added charge; some providers include it, some don't.",
      },
      {
        label: "Out-of-hours or emergency call-out",
        note: "Night, weekend and roadside jobs are often priced above a scheduled daytime visit.",
      },
      {
        label: "Old battery collection",
        note: "The used battery has scrap value. Some quotes deduct it, some quietly keep it.",
      },
      {
        label: "Warranty",
        note: "A 12-month and a 24-month battery at the same price are not the same purchase.",
      },
    ],
  },

  serviceAreas: [
    "Dubai Marina",
    "JLT",
    "Downtown Dubai",
    "Business Bay",
    "Jumeirah",
    "JVC",
    "Al Barsha",
    "Deira",
    "Palm Jumeirah",
  ],

  brands: {
    batteryBrands: [],
    authorizedBrands: [],
  },

  /**
   * Public-facing brand remains "Dubai Battery Service".
   * `partner.name` is used only inside outgoing lead messages and the
   * optional partner-disclosure line — it is never used as the site's
   * brand, headline, or logo text.
   */
    partner: {
    enabled: true,
    name: "Battery Boost Dubai",
    whatsappNumber: "971582424859",
    callNumber: "+971582424859",
  },

  leadAttribution: {
    enabled: true,
    sourceName: "DubaiBatteryService.com",
    includePartnerNameInWhatsAppMessage: true,
  },

  callTracking: {
    enabled: false,
    number: null,
  },

  leadEndpoint: null,

    analytics: {
    gaMeasurementId: "G-5L189EJK9S",
    googleSiteVerification: null,
    googleAdsConversionId: null,
    metaPixelId: null,
  },

  socialLinks: [],
};

/**
 * True only when entityVerified has been explicitly set to true. Being out
 * of "asset" mode is NOT sufficient on its own — operationalMode governs
 * copy tone and lead-handling, not schema.org verification claims.
 */
export const hasVerifiedEntity = siteConfig.entityVerified === true;
